In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import scipy
% matplotlib inline

UsageError: Line magic function `%` not found.

In [4]:
df = pd.read_csv("../Dataset/01 Processed Dataset/Complete_BUF.csv")
df1 = df.set_index('GEOID')
y = df1.pop('obesity_cr')

In [5]:
df1.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
36029000500,0.062950,0.000000,0.000000,0.0,0.153477,0.432854,0.361005,0.118106,0.126499,0.083933,...,0.063401,0.414311,0.331218,50800,1939,0.376904,266.853532,0.243330,0.218783,0.561366
36029000700,0.004076,0.000000,0.007337,0.0,0.029076,0.454891,0.472657,0.165761,0.135870,0.111685,...,0.047530,0.062044,0.100134,125300,1944,0.242323,3437.581736,0.421502,0.413855,0.769681
36029000900,0.005390,0.000000,0.005390,0.0,0.180763,0.484245,0.391390,0.207711,0.227612,0.093284,...,0.078431,0.097015,0.135734,93000,1939,0.445060,4384.936326,0.288562,0.307975,0.621196
36029001000,0.092095,0.034719,0.016137,0.0,0.055094,0.515729,0.427102,0.193154,0.168867,0.082967,...,0.081107,0.207792,0.317936,79400,1939,0.520183,2932.488101,0.362364,0.232738,0.713865
36029001100,0.057063,0.015310,0.032359,0.0,0.105428,0.525052,0.324919,0.186152,0.134308,0.092206,...,0.071886,0.213184,0.239050,74300,1939,0.543430,1885.467988,0.342703,0.188468,0.791351

In [6]:
len(df1), len(y)

(77, 77)

In [7]:
len(df1.columns), df1.columns

(24,
 Index(['% Black', '% Ame Indi and AK Native', '% Asian',
        '% Nati Hawa and Paci Island', '% Hispanic or Latino', '% male',
        '% married', '% age 18-29', '% age 30-39', '% age 40-49', '% age 50-59',
        '% age >=60', '% <highschool', 'median income', '% unemployment',
        '% below poverty line', '% food stamp/SNAP', 'median value units built',
        'median year units built', '% renter-occupied housing units',
        'population density', 'fafood', 'fitness', 'park'],
       dtype='object'))

In [8]:
y.head()

GEOID
36029000500    38.6
36029000700    27.7
36029000900    30.8
36029001000    32.4
36029001100    33.4
Name: obesity_cr, dtype: float64

In [9]:
# Standardization function
def standarize_data(data, stats):
    return (data - stats['mean'])/ stats['std']

df1_stats = df1.describe().transpose()
df_std = standarize_data(df1,df1_stats)

In [10]:
df_std.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
36029000500,-0.972377,-0.481018,-0.665740,-0.268638,0.340632,-0.814688,0.477952,-1.097825,-0.217017,-0.874407,...,-0.392218,0.771001,-0.118599,-0.672453,-0.278485,-1.471619,-1.783293,-0.799178,-0.124349,0.016137
36029000700,-1.149594,-0.481018,-0.569512,-0.268638,-0.745353,-0.378082,1.796983,-0.540475,-0.001039,0.173066,...,-0.690145,-1.765677,-1.507320,0.142833,0.455877,-2.391484,0.204783,1.491490,2.475543,1.646691
36029000900,-1.145640,-0.481018,-0.595051,-0.268638,0.578828,0.203479,0.836913,-0.049846,2.113441,-0.521472,...,-0.110050,-1.513850,-1.293376,-0.210640,-0.278485,-1.005767,0.798783,-0.217646,1.064383,0.484449
36029001000,-0.884647,3.097418,-0.454097,-0.268638,-0.518227,0.827236,1.258804,-0.220101,0.759490,-0.910878,...,-0.059818,-0.716144,-0.198420,-0.359471,-0.278485,-0.492296,-0.111916,0.731182,0.061637,1.209800
36029001100,-0.990095,1.096935,-0.241336,-0.268638,-0.078823,1.011938,0.051631,-0.301996,-0.037040,-0.562145,...,-0.232922,-0.677319,-0.672493,-0.415282,-0.278485,-0.333404,-0.768407,0.478405,-0.528382,1.816315

In [11]:
# Draw graph first

# pd.plotting.scatter_matrix(df_std,figsize=(50,50),
#                   c = 'k',
#                  marker = '+',
#                  diagonal='hist',
#                  alpha = 0.8,
#                  range_padding=0.1)

In [12]:
# Pearson

df_pearson = df_std.corr(method='pearson')
df_pearson.iloc[-1]

# >0.3 
# fafood                             0.314601

% Black                           -0.227055
% Ame Indi and AK Native          -0.014356
% Asian                           -0.225527
% Nati Hawa and Paci Island        0.085539
% Hispanic or Latino              -0.005760
% male                             0.060003
% married                          0.187441
% age 18-29                        0.061236
% age 30-39                        0.017018
% age 40-49                       -0.131793
% age 50-59                        0.106637
% age >=60                         0.100519
% <highschool                     -0.279535
median income                      0.230494
% unemployment                    -0.092650
% below poverty line              -0.248606
% food stamp/SNAP                 -0.249924
median value units built           0.269489
median year units built            0.101350
% renter-occupied housing units   -0.195148
population density                -0.060230
fafood                             0.314601
fitness                            0.279423
park                               1.000000
Name: park, dtype: float64

In [13]:
# Pearson and p-value

col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | -0.2271*
% Ame Indi and AK Native | -0.0144
% Asian | -0.2255*
% Nati Hawa and Paci Island | 0.0855
% Hispanic or Latino | -0.0058
% male | 0.06
% married | 0.1874
% age 18-29 | 0.0612
% age 30-39 | 0.017
% age 40-49 | -0.1318
% age 50-59 | 0.1066
% age >=60 | 0.1005
% <highschool | -0.2795*
median income | 0.2305*
% unemployment | -0.0926
% below poverty line | -0.2486*
% food stamp/SNAP | -0.2499*
median value units built | 0.2695*
median year units built | 0.1013
% renter-occupied housing units | -0.1951
population density | -0.0602
fafood | 0.3146**
fitness | 0.2794*

In [16]:
col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

-0.2271*
-0.0144
-0.2255*
0.0855
-0.0058
0.06
0.1874
0.0612
0.017
-0.1318
0.1066
0.1005
-0.2795*
0.2305*
-0.0926
-0.2486*
-0.2499*
0.2695*
0.1013
-0.1951
-0.0602
0.3146**
0.2794*

In [14]:
# spearman

df_spearman = df_std.corr(method='spearman')
df_spearman.iloc[-1]

# >0.3

% Black                           -0.286135
% Ame Indi and AK Native           0.023673
% Asian                           -0.194640
% Nati Hawa and Paci Island        0.039565
% Hispanic or Latino               0.062227
% male                             0.027446
% married                          0.118723
% age 18-29                       -0.050160
% age 30-39                        0.022188
% age 40-49                       -0.138861
% age 50-59                        0.143751
% age >=60                         0.112835
% <highschool                     -0.236237
median income                      0.181371
% unemployment                    -0.013802
% below poverty line              -0.204427
% food stamp/SNAP                 -0.227168
median value units built           0.180477
median year units built           -0.033489
% renter-occupied housing units   -0.166307
population density                -0.042563
fafood                             0.259162
fitness                            0.286345
park                               1.000000
Name: park, dtype: float64

In [15]:
# spearman and p-value

col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | -0.2861*
% Ame Indi and AK Native | 0.0237
% Asian | -0.1946
% Nati Hawa and Paci Island | 0.0396
% Hispanic or Latino | 0.0622
% male | 0.0274
% married | 0.1187
% age 18-29 | -0.0502
% age 30-39 | 0.0222
% age 40-49 | -0.1389
% age 50-59 | 0.1438
% age >=60 | 0.1128
% <highschool | -0.2362*
median income | 0.1814
% unemployment | -0.0138
% below poverty line | -0.2044
% food stamp/SNAP | -0.2272*
median value units built | 0.1805
median year units built | -0.0335
% renter-occupied housing units | -0.1663
population density | -0.0426
fafood | 0.2592*
fitness | 0.2863*

In [17]:
col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

-0.2861*
0.0237
-0.1946
0.0396
0.0622
0.0274
0.1187
-0.0502
0.0222
-0.1389
0.1438
0.1128
-0.2362*
0.1814
-0.0138
-0.2044
-0.2272*
0.1805
-0.0335
-0.1663
-0.0426
0.2592*
0.2863*