In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import scipy
% matplotlib inline

UsageError: Line magic function `%` not found.

In [3]:
df = pd.read_csv("../Dataset/01 Processed Dataset/Complete_NYC.csv")
df1 = df.set_index('GEOID')
y = df1.pop('obesity_cr')

In [4]:
df1.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
36081046200,0.128637,0.001426,0.405733,0.000000,0.324729,0.429122,0.443847,0.207074,0.149173,0.097119,...,0.056929,0.086140,0.167808,566100,1964,0.776419,28106.912090,0.637197,0.257692,0.590230
36081045000,0.078431,0.000000,0.579115,0.000000,0.191518,0.447788,0.534483,0.176015,0.133151,0.176471,...,0.077815,0.071591,0.076923,585500,1939,0.326454,12744.813160,0.721141,0.374830,0.778180
36081045400,0.160195,0.008653,0.628800,0.000000,0.101176,0.526514,0.550474,0.151986,0.135123,0.197471,...,0.064898,0.147992,0.089735,168400,1954,0.558124,19521.893370,0.421530,0.228491,0.649373
36081045600,0.028744,0.000000,0.708775,0.000000,0.142209,0.486384,0.604982,0.216339,0.116490,0.087746,...,0.081081,0.170197,0.201201,650900,1939,0.279279,8153.246497,0.096508,0.143136,0.324875
36081044602,0.197928,0.011224,0.427585,0.016836,0.298295,0.462335,0.505800,0.136844,0.189294,0.108353,...,0.089128,0.325225,0.340757,281000,1957,0.869339,27255.666740,0.555596,0.268350,0.474746

In [5]:
len(df1), len(y)

(1995, 1995)

In [6]:
len(df1.columns), df1.columns

(24,
 Index(['% Black', '% Ame Indi and AK Native', '% Asian',
        '% Nati Hawa and Paci Island', '% Hispanic or Latino', '% male',
        '% married', '% age 18-29', '% age 30-39', '% age 40-49', '% age 50-59',
        '% age >=60', '% <highschool', 'median income', '% unemployment',
        '% below poverty line', '% food stamp/SNAP', 'median value units built',
        'median year units built', '% renter-occupied housing units',
        'population density', 'fafood', 'fitness', 'park'],
       dtype='object'))

In [7]:
y.head()

GEOID
36081046200    26.6
36081045000    19.6
36081045400    21.5
36081045600    18.6
36081044602    30.6
Name: obesity_cr, dtype: float64

In [8]:
# Standardization function
def standarize_data(data, stats):
    return (data - stats['mean'])/ stats['std']

df1_stats = df1.describe().transpose()
df_std = standarize_data(df1,df1_stats)

In [9]:
df_std.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
36081046200,-0.398834,-0.257814,1.503630,-0.168852,0.312561,-1.236802,-0.054323,0.426032,-0.114064,-1.044443,...,-0.280556,-0.748263,-0.107441,-0.239460,0.993852,0.685575,0.716045,0.853667,-0.759150,-0.533700
36081045000,-0.566402,-0.391848,2.514798,-0.168852,-0.304033,-0.784182,0.747402,-0.038319,-0.404150,1.488031,...,0.260069,-0.879209,-0.742815,-0.179745,-0.779487,-1.137140,-0.465271,1.362547,-0.245224,0.194071
36081045400,-0.293502,0.421420,2.804557,-0.168852,-0.722202,1.124697,0.888855,-0.397565,-0.368442,2.158240,...,-0.074278,-0.191530,-0.653249,-1.463625,0.284516,-0.198694,0.055874,-0.453735,-0.887263,-0.304689
36081045600,-0.732240,-0.391848,3.270972,-0.168852,-0.532273,0.151657,1.371013,0.564554,-0.705803,-1.343592,...,0.344624,0.008333,0.126008,0.021563,-0.779487,-1.328235,-0.818354,-2.424067,-1.261745,-1.561191
36081044602,-0.167564,0.663019,1.631070,5.686315,0.190205,-0.431459,0.493690,-0.623939,0.612356,-0.685917,...,0.552929,1.403739,1.101639,-1.117030,0.497317,1.061977,0.650586,0.358989,-0.712388,-0.980871

In [10]:
# Draw graph first

# pd.plotting.scatter_matrix(df_std,figsize=(50,50),
#                   c = 'k',
#                  marker = '+',
#                  diagonal='hist',
#                  alpha = 0.8,
#                  range_padding=0.1)

In [11]:
# Pearson

df_pearson = df_std.corr(method='pearson')
df_pearson.iloc[-1]

# >0.3 
# % Black                           -0.340004     
# % <highschool                     -0.342008
# median income                      0.369214
# fitness                            0.507157

% Black                           -0.340004
% Ame Indi and AK Native          -0.049612
% Asian                           -0.030441
% Nati Hawa and Paci Island        0.015055
% Hispanic or Latino              -0.171053
% male                             0.033011
% married                          0.239244
% age 18-29                       -0.161317
% age 30-39                       -0.010806
% age 40-49                        0.063200
% age 50-59                        0.099146
% age >=60                         0.247348
% <highschool                     -0.342008
median income                      0.369214
% unemployment                    -0.176967
% below poverty line              -0.248986
% food stamp/SNAP                 -0.279173
median value units built           0.163572
median year units built            0.234559
% renter-occupied housing units   -0.225051
population density                -0.126583
fafood                             0.176847
fitness                            0.507157
park                               1.000000
Name: park, dtype: float64

In [12]:
# Pearson and p-value

col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | -0.34***
% Ame Indi and AK Native | -0.0496*
% Asian | -0.0304
% Nati Hawa and Paci Island | 0.0151
% Hispanic or Latino | -0.1711***
% male | 0.033
% married | 0.2392***
% age 18-29 | -0.1613***
% age 30-39 | -0.0108
% age 40-49 | 0.0632**
% age 50-59 | 0.0991***
% age >=60 | 0.2473***
% <highschool | -0.342***
median income | 0.3692***
% unemployment | -0.177***
% below poverty line | -0.249***
% food stamp/SNAP | -0.2792***
median value units built | 0.1636***
median year units built | 0.2346***
% renter-occupied housing units | -0.2251***
population density | -0.1266***
fafood | 0.1768***
fitness | 0.5072***

In [15]:
col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

-0.34***
-0.0496*
-0.0304
0.0151
-0.1711***
0.033
0.2392***
-0.1613***
-0.0108
0.0632**
0.0991***
0.2473***
-0.342***
0.3692***
-0.177***
-0.249***
-0.2792***
0.1636***
0.2346***
-0.2251***
-0.1266***
0.1768***
0.5072***

In [13]:
# spearman

df_spearman = df_std.corr(method='spearman')
df_spearman.iloc[-1]

# >0.3 
# % Black                           -0.358115
# % <highschool                     -0.343846
# median income                      0.310896
# % food stamp/SNAP                 -0.323464
# fitness                            0.507996

% Black                           -0.358115
% Ame Indi and AK Native          -0.051046
% Asian                            0.109413
% Nati Hawa and Paci Island        0.039765
% Hispanic or Latino              -0.122956
% male                             0.034316
% married                          0.225197
% age 18-29                       -0.240181
% age 30-39                        0.010307
% age 40-49                        0.063618
% age 50-59                        0.059934
% age >=60                         0.234100
% <highschool                     -0.343846
median income                      0.310896
% unemployment                    -0.187899
% below poverty line              -0.247483
% food stamp/SNAP                 -0.323464
median value units built           0.113429
median year units built            0.195557
% renter-occupied housing units   -0.158128
population density                -0.153121
fafood                             0.117265
fitness                            0.507996
park                               1.000000
Name: park, dtype: float64

In [14]:
# spearman and p-value

col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | -0.3581***
% Ame Indi and AK Native | -0.051*
% Asian | 0.1094***
% Nati Hawa and Paci Island | 0.0398
% Hispanic or Latino | -0.123***
% male | 0.0343
% married | 0.2252***
% age 18-29 | -0.2402***
% age 30-39 | 0.0103
% age 40-49 | 0.0636**
% age 50-59 | 0.0599**
% age >=60 | 0.2341***
% <highschool | -0.3438***
median income | 0.3109***
% unemployment | -0.1879***
% below poverty line | -0.2475***
% food stamp/SNAP | -0.3235***
median value units built | 0.1134***
median year units built | 0.1956***
% renter-occupied housing units | -0.1581***
population density | -0.1531***
fafood | 0.1173***
fitness | 0.508***

In [16]:
col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

-0.3581***
-0.051*
0.1094***
0.0398
-0.123***
0.0343
0.2252***
-0.2402***
0.0103
0.0636**
0.0599**
0.2341***
-0.3438***
0.3109***
-0.1879***
-0.2475***
-0.3235***
0.1134***
0.1956***
-0.1581***
-0.1531***
0.1173***
0.508***