In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import scipy
% matplotlib inline

UsageError: Line magic function `%` not found.

In [2]:
df = pd.read_csv("../Dataset/01 Processed Dataset/Complete_LA.csv")
df1 = df.set_index('GEOID')
y = df1.pop('obesity_cr')

In [3]:
df1.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
6037137504,0.009165,0.013025,0.015919,0.000000,0.030873,0.502653,0.550339,0.104197,0.093102,0.112880,...,0.027916,0.043415,0.010086,1185500,1968,0.025937,540.339075,0.808312,0.924512,0.798134
6037138000,0.071474,0.002354,0.071260,0.000000,0.084100,0.514659,0.604255,0.084314,0.126471,0.148727,...,0.073945,0.082602,0.003363,832900,1966,0.172646,1045.182340,0.626115,0.869126,0.754610
6037139200,0.026199,0.000000,0.143836,0.000000,0.227740,0.440925,0.406014,0.153767,0.171062,0.112158,...,0.080120,0.103082,0.028545,560600,1971,0.429098,5070.897045,0.697122,0.827326,0.570550
6037143200,0.091449,0.000000,0.061758,0.006888,0.128029,0.444893,0.334596,0.194299,0.259145,0.160095,...,0.096330,0.108076,0.053769,693300,1977,0.712914,4400.511337,0.474305,0.630256,0.466741
6037143300,0.070877,0.003863,0.072214,0.000000,0.188707,0.484695,0.436177,0.154532,0.158544,0.207875,...,0.059385,0.057219,0.015098,810100,1968,0.595567,4068.456711,0.607633,0.982546,0.762392

In [4]:
len(df1), len(y)

(947, 947)

In [5]:
len(df1.columns), df1.columns

(24,
 Index(['% Black', '% Ame Indi and AK Native', '% Asian',
        '% Nati Hawa and Paci Island', '% Hispanic or Latino', '% male',
        '% married', '% age 18-29', '% age 30-39', '% age 40-49', '% age 50-59',
        '% age >=60', '% <highschool', 'median income', '% unemployment',
        '% below poverty line', '% food stamp/SNAP', 'median value units built',
        'median year units built', '% renter-occupied housing units',
        'population density', 'fafood', 'fitness', 'park'],
       dtype='object'))

In [6]:
y.head()

GEOID
6037137504    22.0
6037138000    23.4
6037139200    24.7
6037143200    23.5
6037143300    23.1
Name: obesity_cr, dtype: float64

In [7]:
# Standardization function
def standarize_data(data, stats):
    return (data - stats['mean'])/ stats['std']

df1_stats = df1.describe().transpose()
df_std = standarize_data(df1,df1_stats)

In [8]:
df_std.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
6037137504,-0.616669,0.426985,-0.879990,-0.328896,-1.552954,0.232056,1.363202,-1.106486,-1.334160,-0.785511,...,-1.316025,-1.230185,-1.080946,1.547590,0.667345,-2.314824,-1.215061,0.336278,1.139070,1.256985
6037138000,-0.102840,-0.384194,-0.399324,-0.328896,-1.368205,0.566856,1.929205,-1.359717,-0.682778,0.377067,...,0.115736,-0.890121,-1.155388,0.544761,0.515519,-1.732550,-1.110385,-0.442527,0.970044,1.026353
6037139200,-0.476206,-0.563141,0.231026,-0.328896,-0.869638,-1.489375,-0.151915,-0.475147,0.187641,-0.808938,...,0.307803,-0.712396,-0.876563,-0.229687,0.895084,-0.714718,-0.275676,-0.139007,0.842484,0.051021
6037143200,0.061879,-0.563141,-0.481859,0.948298,-1.215732,-1.378706,-0.901652,0.041081,1.907053,0.745761,...,0.812046,-0.669060,-0.597278,0.147725,1.350563,0.411722,-0.414676,-1.091446,0.241080,-0.499065
6037143300,-0.107769,-0.269454,-0.391042,-0.328896,-1.005118,-0.268735,0.164743,-0.465406,-0.056711,2.295358,...,-0.337175,-1.110392,-1.025456,0.479916,0.667345,-0.054017,-0.483526,-0.521530,1.316172,1.067590

In [9]:
# Draw graph first

# pd.plotting.scatter_matrix(df_std,figsize=(50,50),
#                   c = 'k',
#                  marker = '+',
#                  diagonal='hist',
#                  alpha = 0.8,
#                  range_padding=0.1)

In [10]:
# Pearson

df_pearson = df_std.corr(method='pearson')
df_pearson.iloc[-1]

# >0.3 
# % Black                           -0.313285    
# % Hispanic or Latino              -0.400971
# % married                          0.411748
# % age >=60                         0.414996
# % <highschool                     -0.431737
# median income                      0.597384
# % below poverty line              -0.401606
# % food stamp/SNAP                 -0.424104
# median value units built           0.519390
# % renter-occupied housing units   -0.389153
# population density                -0.330216
# fitness                            0.597171

% Black                           -0.313285
% Ame Indi and AK Native          -0.013527
% Asian                            0.065736
% Nati Hawa and Paci Island       -0.028112
% Hispanic or Latino              -0.400971
% male                            -0.057038
% married                          0.411748
% age 18-29                       -0.279529
% age 30-39                       -0.079360
% age 40-49                        0.080359
% age 50-59                        0.200333
% age >=60                         0.414996
% <highschool                     -0.431737
median income                      0.597384
% unemployment                    -0.150338
% below poverty line              -0.401606
% food stamp/SNAP                 -0.424104
median value units built           0.519390
median year units built            0.138643
% renter-occupied housing units   -0.389153
population density                -0.330216
fafood                            -0.058178
fitness                            0.597171
park                               1.000000
Name: park, dtype: float64

In [11]:
# Pearson and p-value

col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | -0.3133***
% Ame Indi and AK Native | -0.0135
% Asian | 0.0657*
% Nati Hawa and Paci Island | -0.0281
% Hispanic or Latino | -0.401***
% male | -0.057
% married | 0.4117***
% age 18-29 | -0.2795***
% age 30-39 | -0.0794*
% age 40-49 | 0.0804*
% age 50-59 | 0.2003***
% age >=60 | 0.415***
% <highschool | -0.4317***
median income | 0.5974***
% unemployment | -0.1503***
% below poverty line | -0.4016***
% food stamp/SNAP | -0.4241***
median value units built | 0.5194***
median year units built | 0.1386***
% renter-occupied housing units | -0.3892***
population density | -0.3302***
fafood | -0.0582
fitness | 0.5972***

In [14]:
col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

-0.3133***
-0.0135
0.0657*
-0.0281
-0.401***
-0.057
0.4117***
-0.2795***
-0.0794*
0.0804*
0.2003***
0.415***
-0.4317***
0.5974***
-0.1503***
-0.4016***
-0.4241***
0.5194***
0.1386***
-0.3892***
-0.3302***
-0.0582
0.5972***

In [12]:
# spearman

df_spearman = df_std.corr(method='spearman')
df_spearman.iloc[-1]

# >0.3 
# % Black                           -0.338110
# % Hispanic or Latino              -0.419286
# % married                          0.352966
# % age 18-29                       -0.338636
# % age >=60                         0.398815
# % <highschool                     -0.483362
# median income                      0.553575
# % below poverty line              -0.496012
# % food stamp/SNAP                 -0.509999
# median value units built           0.477849
# % renter-occupied housing units   -0.368519
# population density                -0.422946
# fitness                            0.515639

% Black                           -0.338110
% Ame Indi and AK Native          -0.027781
% Asian                            0.228727
% Nati Hawa and Paci Island       -0.021397
% Hispanic or Latino              -0.419286
% male                            -0.049584
% married                          0.352966
% age 18-29                       -0.338636
% age 30-39                       -0.030737
% age 40-49                        0.077779
% age 50-59                        0.196509
% age >=60                         0.398815
% <highschool                     -0.483362
median income                      0.553575
% unemployment                    -0.144837
% below poverty line              -0.496012
% food stamp/SNAP                 -0.509999
median value units built           0.477849
median year units built            0.180238
% renter-occupied housing units   -0.368519
population density                -0.422946
fafood                            -0.012747
fitness                            0.515639
park                               1.000000
Name: park, dtype: float64

In [13]:
# spearman and p-value

col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | -0.3381***
% Ame Indi and AK Native | -0.0278
% Asian | 0.2287***
% Nati Hawa and Paci Island | -0.0214
% Hispanic or Latino | -0.4193***
% male | -0.0496
% married | 0.353***
% age 18-29 | -0.3386***
% age 30-39 | -0.0307
% age 40-49 | 0.0778*
% age 50-59 | 0.1965***
% age >=60 | 0.3988***
% <highschool | -0.4834***
median income | 0.5536***
% unemployment | -0.1448***
% below poverty line | -0.496***
% food stamp/SNAP | -0.51***
median value units built | 0.4778***
median year units built | 0.1802***
% renter-occupied housing units | -0.3685***
population density | -0.4229***
fafood | -0.0127
fitness | 0.5156***

In [15]:
col = list(df_std)

for vari in col:
    if vari != 'park':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['park'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['park'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

-0.3381***
-0.0278
0.2287***
-0.0214
-0.4193***
-0.0496
0.353***
-0.3386***
-0.0307
0.0778*
0.1965***
0.3988***
-0.4834***
0.5536***
-0.1448***
-0.496***
-0.51***
0.4778***
0.1802***
-0.3685***
-0.4229***
-0.0127
0.5156***