In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import scipy
% matplotlib inline

UsageError: Line magic function `%` not found.

In [2]:
df = pd.read_csv("../Data/01 Processed Dataset/Complete_LA.csv")
df1 = df.set_index('GEOID')
y = df1.pop('obesity_cr')

In [3]:
df1.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
6037137504,0.009165,0.013025,0.015919,0.000000,0.030873,0.502653,0.550339,0.104197,0.093102,0.112880,...,0.027916,0.043415,0.010086,1185500,1968,0.025937,540.339075,0.808312,0.924512,0.798134
6037138000,0.071474,0.002354,0.071260,0.000000,0.084100,0.514659,0.604255,0.084314,0.126471,0.148727,...,0.073945,0.082602,0.003363,832900,1966,0.172646,1045.182340,0.626115,0.869126,0.754610
6037139200,0.026199,0.000000,0.143836,0.000000,0.227740,0.440925,0.406014,0.153767,0.171062,0.112158,...,0.080120,0.103082,0.028545,560600,1971,0.429098,5070.897045,0.697122,0.827326,0.570550
6037143200,0.091449,0.000000,0.061758,0.006888,0.128029,0.444893,0.334596,0.194299,0.259145,0.160095,...,0.096330,0.108076,0.053769,693300,1977,0.712914,4400.511337,0.474305,0.630256,0.466741
6037143300,0.070877,0.003863,0.072214,0.000000,0.188707,0.484695,0.436177,0.154532,0.158544,0.207875,...,0.059385,0.057219,0.015098,810100,1968,0.595567,4068.456711,0.607633,0.982546,0.762392

In [4]:
len(df1), len(y)

(947, 947)

In [5]:
len(df1.columns), df1.columns

(24,
 Index(['% Black', '% Ame Indi and AK Native', '% Asian',
        '% Nati Hawa and Paci Island', '% Hispanic or Latino', '% male',
        '% married', '% age 18-29', '% age 30-39', '% age 40-49', '% age 50-59',
        '% age >=60', '% <highschool', 'median income', '% unemployment',
        '% below poverty line', '% food stamp/SNAP', 'median value units built',
        'median year units built', '% renter-occupied housing units',
        'population density', 'fafood', 'fitness', 'park'],
       dtype='object'))

In [6]:
y.head()

GEOID
6037137504    22.0
6037138000    23.4
6037139200    24.7
6037143200    23.5
6037143300    23.1
Name: obesity_cr, dtype: float64

In [7]:
# Standardization function
def standarize_data(data, stats):
    return (data - stats['mean'])/ stats['std']

df1_stats = df1.describe().transpose()
df_std = standarize_data(df1,df1_stats)

In [8]:
df_std.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
6037137504,-0.616669,0.426985,-0.879990,-0.328896,-1.552954,0.232056,1.363202,-1.106486,-1.334160,-0.785511,...,-1.316025,-1.230185,-1.080946,1.547590,0.667345,-2.314824,-1.215061,0.336278,1.139070,1.256985
6037138000,-0.102840,-0.384194,-0.399324,-0.328896,-1.368205,0.566856,1.929205,-1.359717,-0.682778,0.377067,...,0.115736,-0.890121,-1.155388,0.544761,0.515519,-1.732550,-1.110385,-0.442527,0.970044,1.026353
6037139200,-0.476206,-0.563141,0.231026,-0.328896,-0.869638,-1.489375,-0.151915,-0.475147,0.187641,-0.808938,...,0.307803,-0.712396,-0.876563,-0.229687,0.895084,-0.714718,-0.275676,-0.139007,0.842484,0.051021
6037143200,0.061879,-0.563141,-0.481859,0.948298,-1.215732,-1.378706,-0.901652,0.041081,1.907053,0.745761,...,0.812046,-0.669060,-0.597278,0.147725,1.350563,0.411722,-0.414676,-1.091446,0.241080,-0.499065
6037143300,-0.107769,-0.269454,-0.391042,-0.328896,-1.005118,-0.268735,0.164743,-0.465406,-0.056711,2.295358,...,-0.337175,-1.110392,-1.025456,0.479916,0.667345,-0.054017,-0.483526,-0.521530,1.316172,1.067590

In [10]:
# Draw graph first

# pd.plotting.scatter_matrix(df_std,figsize=(50,50),
#                   c = 'k',
#                  marker = '+',
#                  diagonal='hist',
#                  alpha = 0.8,
#                  range_padding=0.1)

In [9]:
# Pearson

df_pearson = df_std.corr(method='pearson')
df_pearson.iloc[-3]

# >0.3 
# % Black                           -0.340004     
# % <highschool                     -0.342008
# median income                      0.369214
# fitness                            0.507157

% Black                            0.104879
% Ame Indi and AK Native          -0.020391
% Asian                           -0.096585
% Nati Hawa and Paci Island        0.003092
% Hispanic or Latino               0.329484
% male                            -0.005840
% married                          0.193142
% age 18-29                       -0.074976
% age 30-39                       -0.355291
% age 40-49                       -0.075722
% age 50-59                        0.199370
% age >=60                        -0.050908
% <highschool                      0.241646
median income                     -0.191338
% unemployment                     0.046028
% below poverty line               0.022450
% food stamp/SNAP                  0.209667
median value units built          -0.504444
median year units built            0.090202
% renter-occupied housing units   -0.245657
population density                -0.097562
fafood                             1.000000
fitness                           -0.333252
park                              -0.058178
Name: fafood, dtype: float64

In [11]:
# Pearson and p-value

col = list(df_std)

for vari in col:
    if vari != 'fafood':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['fafood'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['fafood'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | 0.1049**
% Ame Indi and AK Native | -0.0204
% Asian | -0.0966**
% Nati Hawa and Paci Island | 0.0031
% Hispanic or Latino | 0.3295***
% male | -0.0058
% married | 0.1931***
% age 18-29 | -0.075*
% age 30-39 | -0.3553***
% age 40-49 | -0.0757*
% age 50-59 | 0.1994***
% age >=60 | -0.0509
% <highschool | 0.2416***
median income | -0.1913***
% unemployment | 0.046
% below poverty line | 0.0224
% food stamp/SNAP | 0.2097***
median value units built | -0.5044***
median year units built | 0.0902**
% renter-occupied housing units | -0.2457***
population density | -0.0976**
fitness | -0.3333***
park | -0.0582

In [12]:
col = list(df_std)

for vari in col:
    if vari != 'fafood':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['fafood'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['fafood'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

0.1049**
-0.0204
-0.0966**
0.0031
0.3295***
-0.0058
0.1931***
-0.075*
-0.3553***
-0.0757*
0.1994***
-0.0509
0.2416***
-0.1913***
0.046
0.0224
0.2097***
-0.5044***
0.0902**
-0.2457***
-0.0976**
-0.3333***
-0.0582

In [13]:
# spearman

df_spearman = df_std.corr(method='spearman')
df_spearman.iloc[-3]

# >0.3 
# % Black                           -0.358115
# % <highschool                     -0.343846
# median income                      0.310896
# % food stamp/SNAP                 -0.323464
# fitness                            0.507996

% Black                            0.081970
% Ame Indi and AK Native           0.057509
% Asian                           -0.091879
% Nati Hawa and Paci Island       -0.038633
% Hispanic or Latino               0.347548
% male                            -0.024559
% married                          0.226735
% age 18-29                       -0.065754
% age 30-39                       -0.334943
% age 40-49                       -0.101028
% age 50-59                        0.196837
% age >=60                        -0.028712
% <highschool                      0.306136
median income                     -0.115396
% unemployment                     0.064045
% below poverty line               0.062894
% food stamp/SNAP                  0.271282
median value units built          -0.439563
median year units built            0.091350
% renter-occupied housing units   -0.252251
population density                -0.081483
fafood                             1.000000
fitness                           -0.292109
park                              -0.012747
Name: fafood, dtype: float64

In [14]:
# spearman and p-value

col = list(df_std)

for vari in col:
    if vari != 'fafood':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['fafood'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['fafood'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | 0.082*
% Ame Indi and AK Native | 0.0575
% Asian | -0.0919**
% Nati Hawa and Paci Island | -0.0386
% Hispanic or Latino | 0.3475***
% male | -0.0246
% married | 0.2267***
% age 18-29 | -0.0658*
% age 30-39 | -0.3349***
% age 40-49 | -0.101**
% age 50-59 | 0.1968***
% age >=60 | -0.0287
% <highschool | 0.3061***
median income | -0.1154***
% unemployment | 0.064*
% below poverty line | 0.0629
% food stamp/SNAP | 0.2713***
median value units built | -0.4396***
median year units built | 0.0914**
% renter-occupied housing units | -0.2523***
population density | -0.0815*
fitness | -0.2921***
park | -0.0127

In [15]:
col = list(df_std)

for vari in col:
    if vari != 'fafood':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['fafood'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['fafood'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

0.082*
0.0575
-0.0919**
-0.0386
0.3475***
-0.0246
0.2267***
-0.0658*
-0.3349***
-0.101**
0.1968***
-0.0287
0.3061***
-0.1154***
0.064*
0.0629
0.2713***
-0.4396***
0.0914**
-0.2523***
-0.0815*
-0.2921***
-0.0127