In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import scipy
% matplotlib inline

UsageError: Line magic function `%` not found.

In [2]:
df = pd.read_csv("../Data/01 Processed Dataset/Complete_NYC.csv")
df1 = df.set_index('GEOID')
y = df1.pop('obesity_cr')

In [3]:
df1.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
36081046200,0.128637,0.001426,0.405733,0.000000,0.324729,0.429122,0.443847,0.207074,0.149173,0.097119,...,0.056929,0.086140,0.167808,566100,1964,0.776419,28106.912090,0.637197,0.257692,0.590230
36081045000,0.078431,0.000000,0.579115,0.000000,0.191518,0.447788,0.534483,0.176015,0.133151,0.176471,...,0.077815,0.071591,0.076923,585500,1939,0.326454,12744.813160,0.721141,0.374830,0.778180
36081045400,0.160195,0.008653,0.628800,0.000000,0.101176,0.526514,0.550474,0.151986,0.135123,0.197471,...,0.064898,0.147992,0.089735,168400,1954,0.558124,19521.893370,0.421530,0.228491,0.649373
36081045600,0.028744,0.000000,0.708775,0.000000,0.142209,0.486384,0.604982,0.216339,0.116490,0.087746,...,0.081081,0.170197,0.201201,650900,1939,0.279279,8153.246497,0.096508,0.143136,0.324875
36081044602,0.197928,0.011224,0.427585,0.016836,0.298295,0.462335,0.505800,0.136844,0.189294,0.108353,...,0.089128,0.325225,0.340757,281000,1957,0.869339,27255.666740,0.555596,0.268350,0.474746

In [4]:
len(df1), len(y)

(1995, 1995)

In [5]:
len(df1.columns), df1.columns

(24,
 Index(['% Black', '% Ame Indi and AK Native', '% Asian',
        '% Nati Hawa and Paci Island', '% Hispanic or Latino', '% male',
        '% married', '% age 18-29', '% age 30-39', '% age 40-49', '% age 50-59',
        '% age >=60', '% <highschool', 'median income', '% unemployment',
        '% below poverty line', '% food stamp/SNAP', 'median value units built',
        'median year units built', '% renter-occupied housing units',
        'population density', 'fafood', 'fitness', 'park'],
       dtype='object'))

In [6]:
y.head()

GEOID
36081046200    26.6
36081045000    19.6
36081045400    21.5
36081045600    18.6
36081044602    30.6
Name: obesity_cr, dtype: float64

In [7]:
# Standardization function
def standarize_data(data, stats):
    return (data - stats['mean'])/ stats['std']

df1_stats = df1.describe().transpose()
df_std = standarize_data(df1,df1_stats)

In [8]:
df_std.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
36081046200,-0.398834,-0.257814,1.503630,-0.168852,0.312561,-1.236802,-0.054323,0.426032,-0.114064,-1.044443,...,-0.280556,-0.748263,-0.107441,-0.239460,0.993852,0.685575,0.716045,0.853667,-0.759150,-0.533700
36081045000,-0.566402,-0.391848,2.514798,-0.168852,-0.304033,-0.784182,0.747402,-0.038319,-0.404150,1.488031,...,0.260069,-0.879209,-0.742815,-0.179745,-0.779487,-1.137140,-0.465271,1.362547,-0.245224,0.194071
36081045400,-0.293502,0.421420,2.804557,-0.168852,-0.722202,1.124697,0.888855,-0.397565,-0.368442,2.158240,...,-0.074278,-0.191530,-0.653249,-1.463625,0.284516,-0.198694,0.055874,-0.453735,-0.887263,-0.304689
36081045600,-0.732240,-0.391848,3.270972,-0.168852,-0.532273,0.151657,1.371013,0.564554,-0.705803,-1.343592,...,0.344624,0.008333,0.126008,0.021563,-0.779487,-1.328235,-0.818354,-2.424067,-1.261745,-1.561191
36081044602,-0.167564,0.663019,1.631070,5.686315,0.190205,-0.431459,0.493690,-0.623939,0.612356,-0.685917,...,0.552929,1.403739,1.101639,-1.117030,0.497317,1.061977,0.650586,0.358989,-0.712388,-0.980871

In [10]:
# Draw graph first

# pd.plotting.scatter_matrix(df_std,figsize=(50,50),
#                   c = 'k',
#                  marker = '+',
#                  diagonal='hist',
#                  alpha = 0.8,
#                  range_padding=0.1)

In [11]:
# Pearson

df_pearson = df_std.corr(method='pearson')
df_pearson.iloc[-3]

# >0.3 
# % Black                           -0.340004     
# % <highschool                     -0.342008
# median income                      0.369214
# fitness                            0.507157

% Black                            0.104192
% Ame Indi and AK Native          -0.013346
% Asian                            0.049892
% Nati Hawa and Paci Island        0.016553
% Hispanic or Latino               0.095576
% male                            -0.027777
% married                          0.120834
% age 18-29                       -0.150295
% age 30-39                       -0.297042
% age 40-49                        0.106486
% age 50-59                        0.296677
% age >=60                         0.092214
% <highschool                      0.068583
median income                     -0.170513
% unemployment                     0.086975
% below poverty line              -0.126574
% food stamp/SNAP                 -0.029110
median value units built          -0.405914
median year units built            0.115037
% renter-occupied housing units   -0.296519
population density                -0.269176
fafood                             1.000000
fitness                           -0.144282
park                               0.176847
Name: fafood, dtype: float64

In [13]:
# Pearson and p-value

col = list(df_std)

for vari in col:
    if vari != 'fafood':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['fafood'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['fafood'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | 0.1042***
% Ame Indi and AK Native | -0.0133
% Asian | 0.0499*
% Nati Hawa and Paci Island | 0.0166
% Hispanic or Latino | 0.0956***
% male | -0.0278
% married | 0.1208***
% age 18-29 | -0.1503***
% age 30-39 | -0.297***
% age 40-49 | 0.1065***
% age 50-59 | 0.2967***
% age >=60 | 0.0922***
% <highschool | 0.0686**
median income | -0.1705***
% unemployment | 0.087***
% below poverty line | -0.1266***
% food stamp/SNAP | -0.0291
median value units built | -0.4059***
median year units built | 0.115***
% renter-occupied housing units | -0.2965***
population density | -0.2692***
fitness | -0.1443***
park | 0.1768***

In [14]:
col = list(df_std)

for vari in col:
    if vari != 'fafood':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['fafood'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['fafood'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

0.1042***
-0.0133
0.0499*
0.0166
0.0956***
-0.0278
0.1208***
-0.1503***
-0.297***
0.1065***
0.2967***
0.0922***
0.0686**
-0.1705***
0.087***
-0.1266***
-0.0291
-0.4059***
0.115***
-0.2965***
-0.2692***
-0.1443***
0.1768***

In [15]:
# spearman

df_spearman = df_std.corr(method='spearman')
df_spearman.iloc[-3]

# >0.3 
# % Black                           -0.358115
# % <highschool                     -0.343846
# median income                      0.310896
# % food stamp/SNAP                 -0.323464
# fitness                            0.507996

% Black                            0.074124
% Ame Indi and AK Native           0.006169
% Asian                            0.033114
% Nati Hawa and Paci Island        0.021723
% Hispanic or Latino               0.134197
% male                            -0.017274
% married                          0.114259
% age 18-29                       -0.122639
% age 30-39                       -0.266072
% age 40-49                        0.118612
% age 50-59                        0.305104
% age >=60                         0.141312
% <highschool                      0.125918
median income                     -0.051605
% unemployment                     0.118482
% below poverty line              -0.105563
% food stamp/SNAP                  0.020902
median value units built          -0.354550
median year units built            0.155585
% renter-occupied housing units   -0.271277
population density                -0.295835
fafood                             1.000000
fitness                           -0.071600
park                               0.117265
Name: fafood, dtype: float64

In [16]:
# spearman and p-value

col = list(df_std)

for vari in col:
    if vari != 'fafood':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['fafood'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['fafood'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | 0.0741***
% Ame Indi and AK Native | 0.0062
% Asian | 0.0331
% Nati Hawa and Paci Island | 0.0217
% Hispanic or Latino | 0.1342***
% male | -0.0173
% married | 0.1143***
% age 18-29 | -0.1226***
% age 30-39 | -0.2661***
% age 40-49 | 0.1186***
% age 50-59 | 0.3051***
% age >=60 | 0.1413***
% <highschool | 0.1259***
median income | -0.0516*
% unemployment | 0.1185***
% below poverty line | -0.1056***
% food stamp/SNAP | 0.0209
median value units built | -0.3545***
median year units built | 0.1556***
% renter-occupied housing units | -0.2713***
population density | -0.2958***
fitness | -0.0716**
park | 0.1173***

In [17]:
col = list(df_std)

for vari in col:
    if vari != 'fafood':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['fafood'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['fafood'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

0.0741***
0.0062
0.0331
0.0217
0.1342***
-0.0173
0.1143***
-0.1226***
-0.2661***
0.1186***
0.3051***
0.1413***
0.1259***
-0.0516*
0.1185***
-0.1056***
0.0209
-0.3545***
0.1556***
-0.2713***
-0.2958***
-0.0716**
0.1173***