In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import scipy
% matplotlib inline

UsageError: Line magic function `%` not found.

In [2]:
df = pd.read_csv("../Data/01 Processed Dataset/Complete_BUF.csv")
df1 = df.set_index('GEOID')
y = df1.pop('obesity_cr')

In [3]:
df1.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
36029000500,0.062950,0.000000,0.000000,0.0,0.153477,0.432854,0.361005,0.118106,0.126499,0.083933,...,0.063401,0.414311,0.331218,50800,1939,0.376904,266.853532,0.243330,0.218783,0.561366
36029000700,0.004076,0.000000,0.007337,0.0,0.029076,0.454891,0.472657,0.165761,0.135870,0.111685,...,0.047530,0.062044,0.100134,125300,1944,0.242323,3437.581736,0.421502,0.413855,0.769681
36029000900,0.005390,0.000000,0.005390,0.0,0.180763,0.484245,0.391390,0.207711,0.227612,0.093284,...,0.078431,0.097015,0.135734,93000,1939,0.445060,4384.936326,0.288562,0.307975,0.621196
36029001000,0.092095,0.034719,0.016137,0.0,0.055094,0.515729,0.427102,0.193154,0.168867,0.082967,...,0.081107,0.207792,0.317936,79400,1939,0.520183,2932.488101,0.362364,0.232738,0.713865
36029001100,0.057063,0.015310,0.032359,0.0,0.105428,0.525052,0.324919,0.186152,0.134308,0.092206,...,0.071886,0.213184,0.239050,74300,1939,0.543430,1885.467988,0.342703,0.188468,0.791351

In [4]:
len(df1), len(y)

(77, 77)

In [5]:
len(df1.columns), df1.columns

(24,
 Index(['% Black', '% Ame Indi and AK Native', '% Asian',
        '% Nati Hawa and Paci Island', '% Hispanic or Latino', '% male',
        '% married', '% age 18-29', '% age 30-39', '% age 40-49', '% age 50-59',
        '% age >=60', '% <highschool', 'median income', '% unemployment',
        '% below poverty line', '% food stamp/SNAP', 'median value units built',
        'median year units built', '% renter-occupied housing units',
        'population density', 'fafood', 'fitness', 'park'],
       dtype='object'))

In [6]:
y.head()

GEOID
36029000500    38.6
36029000700    27.7
36029000900    30.8
36029001000    32.4
36029001100    33.4
Name: obesity_cr, dtype: float64

In [7]:
# Standardization function
def standarize_data(data, stats):
    return (data - stats['mean'])/ stats['std']

df1_stats = df1.describe().transpose()
df_std = standarize_data(df1,df1_stats)

In [8]:
df_std.head()

,% Black,% Ame Indi and AK Native,% Asian,% Nati Hawa and Paci Island,% Hispanic or Latino,% male,% married,% age 18-29,% age 30-39,% age 40-49,...,% unemployment,% below poverty line,% food stamp/SNAP,median value units built,median year units built,% renter-occupied housing units,population density,fafood,fitness,park
GEOID,,,,,,,,,,,,,,,,,,,,,
36029000500,-0.972377,-0.481018,-0.665740,-0.268638,0.340632,-0.814688,0.477952,-1.097825,-0.217017,-0.874407,...,-0.392218,0.771001,-0.118599,-0.672453,-0.278485,-1.471619,-1.783293,-0.799178,-0.124349,0.016137
36029000700,-1.149594,-0.481018,-0.569512,-0.268638,-0.745353,-0.378082,1.796983,-0.540475,-0.001039,0.173066,...,-0.690145,-1.765677,-1.507320,0.142833,0.455877,-2.391484,0.204783,1.491490,2.475543,1.646691
36029000900,-1.145640,-0.481018,-0.595051,-0.268638,0.578828,0.203479,0.836913,-0.049846,2.113441,-0.521472,...,-0.110050,-1.513850,-1.293376,-0.210640,-0.278485,-1.005767,0.798783,-0.217646,1.064383,0.484449
36029001000,-0.884647,3.097418,-0.454097,-0.268638,-0.518227,0.827236,1.258804,-0.220101,0.759490,-0.910878,...,-0.059818,-0.716144,-0.198420,-0.359471,-0.278485,-0.492296,-0.111916,0.731182,0.061637,1.209800
36029001100,-0.990095,1.096935,-0.241336,-0.268638,-0.078823,1.011938,0.051631,-0.301996,-0.037040,-0.562145,...,-0.232922,-0.677319,-0.672493,-0.415282,-0.278485,-0.333404,-0.768407,0.478405,-0.528382,1.816315

In [9]:
# Draw graph first

# pd.plotting.scatter_matrix(df_std,figsize=(50,50),
#                   c = 'k',
#                  marker = '+',
#                  diagonal='hist',
#                  alpha = 0.8,
#                  range_padding=0.1)

In [10]:
# Pearson

df_pearson = df_std.corr(method='pearson')
df_pearson.iloc[-2]

# >0.3 
# % Black                           -0.340004     
# % <highschool                     -0.342008
# median income                      0.369214
# fitness                            0.507157

% Black                           -0.531987
% Ame Indi and AK Native           0.062385
% Asian                            0.029174
% Nati Hawa and Paci Island        0.013254
% Hispanic or Latino               0.029334
% male                             0.228583
% married                          0.294741
% age 18-29                        0.248772
% age 30-39                        0.270071
% age 40-49                        0.016830
% age 50-59                       -0.109300
% age >=60                        -0.021698
% <highschool                     -0.323184
median income                      0.561550
% unemployment                    -0.518480
% below poverty line              -0.477645
% food stamp/SNAP                 -0.530748
median value units built           0.481572
median year units built           -0.074851
% renter-occupied housing units   -0.184636
population density                 0.284615
fafood                             0.071463
fitness                            1.000000
park                               0.279423
Name: fitness, dtype: float64

In [11]:
# Pearson and p-value

col = list(df_std)

for vari in col:
    if vari != 'fitness':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['fitness'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['fitness'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | -0.532***
% Ame Indi and AK Native | 0.0624
% Asian | 0.0292
% Nati Hawa and Paci Island | 0.0133
% Hispanic or Latino | 0.0293
% male | 0.2286*
% married | 0.2947**
% age 18-29 | 0.2488*
% age 30-39 | 0.2701*
% age 40-49 | 0.0168
% age 50-59 | -0.1093
% age >=60 | -0.0217
% <highschool | -0.3232**
median income | 0.5615***
% unemployment | -0.5185***
% below poverty line | -0.4776***
% food stamp/SNAP | -0.5307***
median value units built | 0.4816***
median year units built | -0.0749
% renter-occupied housing units | -0.1846
population density | 0.2846*
fafood | 0.0715
park | 0.2794*

In [12]:
col = list(df_std)

for vari in col:
    if vari != 'fitness':
        coffi = scipy.stats.pearsonr(df_std[vari], df_std['fitness'])[0].round(4)
        p_value = scipy.stats.pearsonr(df_std[vari], df_std['fitness'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

-0.532***
0.0624
0.0292
0.0133
0.0293
0.2286*
0.2947**
0.2488*
0.2701*
0.0168
-0.1093
-0.0217
-0.3232**
0.5615***
-0.5185***
-0.4776***
-0.5307***
0.4816***
-0.0749
-0.1846
0.2846*
0.0715
0.2794*

In [13]:
# spearman

df_spearman = df_std.corr(method='spearman')
df_spearman.iloc[-2]

# >0.3 
# % Black                           -0.358115
# % <highschool                     -0.343846
# median income                      0.310896
# % food stamp/SNAP                 -0.323464
# fitness                            0.507996

% Black                           -0.579421
% Ame Indi and AK Native           0.036544
% Asian                            0.066488
% Nati Hawa and Paci Island        0.037430
% Hispanic or Latino               0.154319
% male                             0.228640
% married                          0.295731
% age 18-29                        0.340764
% age 30-39                        0.285662
% age 40-49                        0.030338
% age 50-59                       -0.107025
% age >=60                         0.005679
% <highschool                     -0.437668
median income                      0.612808
% unemployment                    -0.581261
% below poverty line              -0.505074
% food stamp/SNAP                 -0.565645
median value units built           0.687628
median year units built            0.050730
% renter-occupied housing units   -0.155055
population density                 0.313686
fafood                             0.117409
fitness                            1.000000
park                               0.286345
Name: fitness, dtype: float64

In [14]:
# spearman and p-value

col = list(df_std)

for vari in col:
    if vari != 'fitness':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['fitness'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['fitness'])[1]
        if p_value < 0.001:
            print(vari + " | " + str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(vari + " | " + str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(vari + " | " + str(coffi) + "*") 
        if p_value >= 0.05:
            print(vari + " | " + str(coffi))

% Black | -0.5794***
% Ame Indi and AK Native | 0.0365
% Asian | 0.0665
% Nati Hawa and Paci Island | 0.0374
% Hispanic or Latino | 0.1543
% male | 0.2286*
% married | 0.2957**
% age 18-29 | 0.3408**
% age 30-39 | 0.2857*
% age 40-49 | 0.0303
% age 50-59 | -0.107
% age >=60 | 0.0057
% <highschool | -0.4377***
median income | 0.6128***
% unemployment | -0.5813***
% below poverty line | -0.5051***
% food stamp/SNAP | -0.5656***
median value units built | 0.6876***
median year units built | 0.0507
% renter-occupied housing units | -0.1551
population density | 0.3137**
fafood | 0.1174
park | 0.2863*

In [15]:
col = list(df_std)

for vari in col:
    if vari != 'fitness':
        coffi = scipy.stats.spearmanr(df_std[vari], df_std['fitness'])[0].round(4)
        p_value = scipy.stats.spearmanr(df_std[vari], df_std['fitness'])[1]
        if p_value < 0.001:
            print(str(coffi) + "***") 
        if p_value < 0.01 and p_value >= 0.001:
            print(str(coffi) + "**") 
        if p_value < 0.05 and p_value >= 0.01:
            print(str(coffi) + "*") 
        if p_value >= 0.05:
            print(str(coffi))

-0.5794***
0.0365
0.0665
0.0374
0.1543
0.2286*
0.2957**
0.3408**
0.2857*
0.0303
-0.107
0.0057
-0.4377***
0.6128***
-0.5813***
-0.5051***
-0.5656***
0.6876***
0.0507
-0.1551
0.3137**
0.1174
0.2863*